### ISSUE TITLE
Bug - Naming Convention

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/stockmanagement-core#1]
Bug : Use proper naming conventions for class name.

![image](https://user-images.githubusercontent.com/22638364/126104621-52e6bf31-3ab8-44ea-a6b7-94c77f82f080.png)
![image](https://user-images.githubusercontent.com/22638364/126104643-62edb640-ee04-49b3-9fb9-cf48d155ce84.png)
![image](https://user-images.githubusercontent.com/22638364/126104678-ab735bf3-983f-4020-8067-5f464099adaa.png)

**Comment by rssaran** [comment]
Name convention for exportdetails has been fixed

**Comment by venkatvs22** [comment]
Name convention For ImportDetails has been fixed
