### ISSUE TITLE
Bug - Feature - Save Export details

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/stockmanagement-core#2]
Scenario:
As a user. I have to save the new export details

Bug: Table created in "EXPORT_DETAILS TABLE" name and trying to insert in "Export" table from DAO.

![image](https://user-images.githubusercontent.com/22638364/126105011-14e9de67-b34e-44a7-9561-dac545ca92c0.png)

![image](https://user-images.githubusercontent.com/22638364/126104844-5393ae58-7d90-4043-9773-70532cbe49f3.png)

**Comment by rssaran** [comment]
BUG ha been fixed....Export renamed has Export_Details
