### ISSUE TITLE
Bug : model class missing 

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/stockmanagement-core#3]
In Git - push, some model files are missing. 

![image](https://user-images.githubusercontent.com/22638364/126105361-e27362be-ca38-4880-9bd2-b691a577d203.png)

**Comment by rssaran** [comment]
I have resubmitted my export and tracking validator model mam

**Comment by venkatvs22** [comment]
I have resubmitted my Import and Product Model mam
